### ISSUE TITLE
Windows getting error "npm ERR! code ELIFECYCLE".

### ISSUE THREAD

**Issue by rajaramtt** [framework7io/framework7-template-single-view#1]
Windows getting error "npm ERR! code ELIFECYCLE".
Same example working in Ubuntu 
![image](https://user-images.githubusercontent.com/17231665/34078791-47d55948-e347-11e7-825c-4d94f277f249.png)

**Comment by dobrys** [comment]
you should add this :
"config": {
    "unsafe-perm":true
}

**Comment by dobrys** [comment]
or run "npm install --unsafe-perm"
